apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: kqtwe3hiq-go
  janus-idp.io/tekton: kqtwe3hiq-go
  backstage.io/kubernetes-id: kqtwe3hiq-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kqtwe3hiq-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
